export default [
    {
        id: 0,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: false,
    },
    {
        id: 1,
    img: "/product__6.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: true,
    },
    {
        id: 2,
    img: "/product__19.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: false,
    },
    {
        id: 3,
    img: "/product__23.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: false,
    },
    {
        id: 4,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: false,
    },
    {
        id: 5,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: false,
    },
    {
        id: 6,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["lipsticks"],
    sale: false,
    },
    {
        id: 7,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 8,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 9,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 10,
    img: "/product__6.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 11,
    img: "/product__19.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 12,
    img: "/product__23.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 13,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["skin care"],
    sale: false,
    },
    {
        id: 14,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 15,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 16,
    img: "/product__6.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 17,
    img: "/product__23.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 18,
    img: "/product__19.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 19,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 20,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 21,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 22,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["makeup"],
    sale: false,
    },
    {
        id: 23,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 24,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 25,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 26,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 27,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 28,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 29,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 30,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
    {
        id: 31,
    img: "/product__2.webp",
    name: "Wild Skin Finish Lipistick",
    price: 51.0,
    category: ["nail & wax"],
    sale: false,
    },
];
