export default [
    {
        id: 0,
    img: "/causal1.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 514.0,
    offer: 30,
    stars: 3,
    category: ["casual"],
    sale: false,
    },
    {
        id: 1,
    img: "/causal2.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 501.0,
    offer: 12,
    stars: 4,
    category: ["casual"],
    sale: true,
    },
    {
        id: 2,
    img: "/causal3.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 530.0,
    offer: 18,
    stars: 5,
    category: ["casual"],
    sale: false,
    },
    {
        id: 3,
    img: "/causal4.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 559.0,
    offer: 22,
    stars: 3,
    category: ["casual"],
    sale: false,
    },
    {
        id: 4,
    img: "/causal5.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 680.0,
    offer: 21,
    stars: 4,
    category: ["casual"],
    sale: false,
    },
    {
        id: 5,
    img: "/causal6.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 987.0,
    offer: 29,
    stars: 4,
    category: ["casual"],
    sale: false,
    },
    {
        id: 6,
    img: "/causal7.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 480.0,
    offer: 14,
    stars: 4,
    category: ["casual"],
    sale: false,
    },
    {
        id: 7,
    img: "/causal8.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 531.0,
    offer: 25,
    stars: 3,
    category: ["casual"],
    sale: false,
    },
    {
        id: 8,
    img: "/causal9.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 591.0,
    offer: 33,
    stars: 5,
    category: ["casual"],
    sale: true,
    },
    {
        id: 9,
    img: "/causal10.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 865.0,
    offer: 39,
    stars: 3,
    category: ["casual"],
    sale: true,
    },
    {
        id: 10,
    img: "/causal11.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 601.0,
    offer: 11,
    stars: 2,
    category: ["casual"],
    sale: true,
    },
    {
        id: 11,
    img: "/causal12.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 732.0,
    offer: 33,
    stars: 4,
    category: ["casual"],
    sale: true,
    },
    {
        id: 12,
    img: "/causal13.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 1401.0,
    offer: 44,
    stars: 5,
    category: ["casual"],
    sale: true,
    },
    {
        id: 13,
    img: "/causal14.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 1134.0,
    offer: 46,
    stars: 4,
    category: ["casual"],
    sale: true,
    },
    {
        id: 14,
    img: "/causal15.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 401.0,
    offer: 6,
    stars: 3,
    category: ["casual"],
    sale: true,
    },
    {
        id: 15,
    img: "/causal16.webp",
    name: "HOP Kids Beige Leaf Abstract Printed Shirt",
    price: 571.0,
    offer: 8,
    stars: 3,
    category: ["casual"],
    sale: true,
    },
    {
        id: 16,
    img: "/jeans1.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 549.0,
    offer: 2,
    stars: 5,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 17,
    img: "/jeans2.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 875.0,
    offer: 4,
    stars: 4,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 18,
    img: "/jeans3.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 674.0,
    offer: 7,
    stars: 4,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 19,
    img: "/jeans4.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 975.0,
    offer: 9,
    stars: 4,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 20,
    img: "/jeans5.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 867.0,
    offer: 22,
    stars: 4,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 21,
    img: "/jeans6.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 783.0,
    offer: 6,
    stars: 4,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 22,
    img: "/jeans7.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 459.0,
    offer: 8,
    stars: 4,
    category: ["jeans"],
    sale: false,
    },
    {
        id: 23,
    img: "/jeans8.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 789.0,
    offer: 5,
    stars: 2,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 24,
    img: "/jeans9.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 874.0,
    offer: 11,
    stars: 3,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 25,
    img: "/jeans10.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 679.0,
    offer: 6,
    stars: 4,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 26,
    img: "/jeans11.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 860.0,
    offer: 6,
    stars: 2,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 27,
    img: "/jeans12.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 374.0,
    offer: 2,
    stars: 2,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 28,
    img: "/jeans13.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 856.0,
    offer: 16,
    stars: 3,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 29,
    img: "/jeans14.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 987.0,
    offer: 28,
    stars: 3,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 30,
    img: "/jeans15.webp",
    name: "CAVIO Boys Regular Fit Denim Short",
    price: 691.0,
    offer: 16,
    stars: 5,
    category: ["jeans"],
    sale: true,
    },
    {
        id: 31,
    img: "/tshart1.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 793.0,
    offer: 6,
    stars: 3,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 32,
    img: "/tshart2.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 834.0,
    offer: 4,
    stars: 2,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 33,
    img: "/tshart3.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 857.0,
    offer: 9,
    stars: 5,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 34,
    img: "/tshart4.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 828.0,
    offer: 4,
    stars: 2,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 35,
    img: "/tshart5.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 478.0,
    offer: 12,
    stars: 3,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 36,
    img: "/tshart6.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 517.0,
    offer: 9,
    stars: 2,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 37,
    img: "/tshart7.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 590.0,
    offer: 7,
    stars: 4,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 38,
    img: "/tshart8.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 980.0,
    offer: 9,
    stars: 4,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 39,
    img: "/tshart9.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 999.0,
    offer: 3,
    stars: 5,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 40,
    img: "/tshart10.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 870.0,
    offer: 5,
    stars: 4,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 41,
    img: "/tshart11.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 356.0,
    offer: 3,
    stars: 4,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 42,
    img: "/tshart12.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 613.0,
    offer: 3,
    stars: 3,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 43,
    img: "/tshart13.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 984.0,
    offer: 13,
    stars: 3,
    category: ["tshart"],
    sale: false,
    },
    {
        id: 44,
    img: "/tshart14.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 689.0,
    offer: 30,
    stars: 3,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 45,
    img: "/tshart15.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 851.0,
    offer: 6,
    stars: 2,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 46,
    img: "/tshart16.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 851.0,
    offer: 22,
    stars: 3,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 47,
    img: "/tshart17.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 651.0,
    offer: 6,
    stars: 4,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 48,
    img: "/tshart18.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 751.0,
    offer: 11,
    stars: 5,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 49,
    img: "/tshart19.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 763.0,
    offer: 35,
    stars: 4,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 50,
    img: "/tshart20.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 824.0,
    offer: 35,
    stars: 3,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 51,
    img: "/tshart21.jpg",
    name: "SIMPLE STRIPES MODERN ART BOYES T-SHIRT",
    price: 535.0,
    offer: 6,
    stars: 2,
    category: ["tshart"],
    sale: true,
    },
    {
        id: 52,
    img: "/shart1.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 724.0,
    offer: 35,
    stars: 1,
    category: ["formal"],
    sale: false,
    },
    {
        id: 53,
    img: "/shart2.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 847.0,
    offer: 25,
    stars: 5,
    category: ["formal"],
    sale: false,
    },
    {
        id: 54,
    img: "/shart3.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 451.0,
    offer: 2,
    stars: 3,
    category: ["formal"],
    sale: false,
    },
    {
        id: 55,
    img: "/shart4.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 865.0,
    offer: 44,
    stars: 2,
    category: ["formal"],
    sale: false,
    },
    {
        id: 56,
    img: "/shart5.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 446.0,
    offer: 26,
    stars: 4,
    category: ["formal"],
    sale: false,
    },
    {
        id: 57,
    img: "/shart6.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 967.0,
    offer: 29,
    stars: 4,
    category: ["formal"],
    sale: false,
    },
    {
        id: 58,
    img: "/shart7.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 978.0,
    offer: 30,
    stars: 4,
    category: ["formal"],
    sale: false,
    },
    {
        id: 59,
    img: "/shart8.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 834.0,
    offer: 22,
    stars: 5,
    category: ["formal"],
    sale: true,
    },
    {
        id: 60,
    img: "/shart9.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 976.0,
    offer: 24,
    stars: 4,
    category: ["formal"],
    sale: true,
    },
    {
        id: 61,
    img: "/shart10.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 786.0,
    offer: 10,
    stars: 3,
    category: ["formal"],
    sale: true,
    },
    {
        id: 62,
    img: "/shart11.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 591.0,
    offer: 14,
    stars: 3,
    category: ["formal"],
    sale: true,
    },
    {
        id: 63,
    img: "/shart12.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 516.0,
    offer: 17,
    stars: 6,
    category: ["formal"],
    sale: true,
    },
    {
        id: 64,
    img: "/shart13.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 739.0,
    offer: 25,
    stars: 3,
    category: ["formal"],
    sale: true,
    },
    {
        id: 65,
    img: "/shart14.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 897.0,
    offer: 9,
    stars: 5,
    category: ["formal"],
    sale: true,
    },
    {
        id: 66,
    img: "/shart15.webp",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 678.0,
    offer: 26,
    stars: 4,
    category: ["formal"],
    sale: true,
    },
];
